spring.application.name=backend
server.port=8081

# Importa o arquivo .env local automaticamente para o Spring
spring.config.import=optional:file:.env[.properties]

# Conexão com o Postgres usando as variáveis seguras
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true